export const CLIENT_ID = "1002830266049-m6m738su63n9fu2i9plcsq6g6bnhmko4.apps.googleusercontent.com"
export const CLIENT_SECRET="bAd7gSGnxkoyQ5qmZMxML9bC"
export const REDIRECT_URI= "http://localhost:3006/oauth-callback/"
export const SCOPE="profile email"
export const RESPONSE_TYPE="token"
export const STATE="google"
export const PROMPT="select_account"